language: smalltalk
sudo: enabled

os:
  - linux

smalltalk:
  - Pharo-7.0
  - Pharo-6.1
  - Pharo64-7.0
  
services:
  - postgresql
  
addons:
  postgresql: "9.6"

before_script:
  - psql -U postgres -c 'DROP TABLE IF EXISTS abcdef'
